In [1]:
# Import library numpy
import numpy as np

# Membuat array 1 dimensi
array_1d = np.array([1, 2, 3, 4, 5])
print("Array 1D:", array_1d)

# Membuat array 2 dimensi
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("Array 2D:\n", array_2d)

# Membuat array dengan nilai nol
array_zeros = np.zeros((3, 3))
print("Array dengan nilai nol:\n", array_zeros)

# Membuat array dengan nilai satu
array_ones = np.ones((2, 4))
print("Array dengan nilai satu:\n", array_ones)

# Membuat array dengan nilai acak
array_random = np.random.random((2, 2))
print("Array dengan nilai acak:\n", array_random)

# Mengakses elemen array
elemen = array_1d[2]
print("Elemen ketiga dari array_1d:", elemen)

# Mengubah elemen array
array_1d[2] = 10
print("Array 1D setelah diubah:", array_1d)

# Operasi aritmatika pada array
array_sum = array_1d + 5
print("Array 1D setelah ditambah 5:", array_sum)

# Menghitung rata-rata dari array
mean_value = np.mean(array_1d)
print("Rata-rata dari array_1d:", mean_value)

Array 1D: [1 2 3 4 5]
Array 2D:
 [[1 2 3]
 [4 5 6]]
Array dengan nilai nol:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Array dengan nilai satu:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Array dengan nilai acak:
 [[0.10601528 0.8272721 ]
 [0.62391783 0.07403098]]
Elemen ketiga dari array_1d: 3
Array 1D setelah diubah: [ 1  2 10  4  5]
Array 1D setelah ditambah 5: [ 6  7 15  9 10]
Rata-rata dari array_1d: 4.4
